---
title: "Homework4 DDS"
author: "Adam Baca"
date: "October 24, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Bootstrap Example



```{r cars}
boottest<-rexp(200,6)
mean(boottest)
1/mean(boottest)
L<-1/mean(boottest)
CIlow<-L-qnorm(0.975)*L/sqrt(200)
CIhigh<-L+qnorm(0.975)*L/sqrt(200)
boot<-matrix(1,1500)
for (i in 1:1500){
boot[i]<-1/mean(rexp(200,L))
}
windows()
hist(boot,main="Estimate of sampling distribution of L",breaks=50)
my.quantiles<-quantile(boot,c(.025,0.975))
CIbootlow<-2*L-my.quantiles[2]
CIboothigh<-2*L-my.quantiles[1]
boot.est<-sqrt(var(boot))
boot.est
boottest<-pexp(20,1,lower.tail=TRUE,log.p=FALSE)
mean(boottest)
1/mean(boottest)
L<-mean(boottest)
CIlow<-L-qnorm(0.975)*L/sqrt(20)
CIhigh<-L+qnorm(0.975)*L/sqrt(20)
boot<-matrix(1,1500)
for (i in 1:1500){
boot[i]<-mean(pexp(20,1,lower.tail=TRUE,log.p=FALSE))
}
windows()
hist(boot,main="Non Exp",breaks=5)
my.quantiles<-quantile(boot,c(.025,0.975))
CIbootlow<-2*L-my.quantiles[2]
CIboothigh<-2*L-my.quantiles[1]
boot.est<-sqrt(var(boot))
boot.est
```




